# 02. PyTorch Tensors Tutorial

**Goals:** get understadning how to work with tensors in PyTorch.

**Source:** [PyTorch Docs Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

This notebook will provide examples and explanations of basic operations with tensors.

In [1]:
import torch
import numpy as np

## 1. Initialization of Tensors

Tesors can be created in different ways: from data, from numpy, from another tensor, using random/constant value generators.

In [2]:
# Initializating from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# From a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# From another tensor (the same shape, but another data)
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the dataype of x_data

# Using random/constant value generators
shape = (2, 3,)
zeros_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)

print("x_data:\n", x_data)
print("x_np:\n", x_np)
print("x_ones\n", x_ones)
print("x_rand\n", x_rand)
print("zeros_tensor:\n", zeros_tensor)
print("ones_tensor:\n", ones_tensor)
print("rand_tensor:\n", rand_tensor)

x_data:
 tensor([[1, 2],
        [3, 4]])
x_np:
 tensor([[1, 2],
        [3, 4]])
x_ones
 tensor([[1, 1],
        [1, 1]])
x_rand
 tensor([[0.5829, 0.3514],
        [0.5577, 0.7099]])
zeros_tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones_tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand_tensor:
 tensor([[0.4026, 0.7114, 0.9271],
        [0.5106, 0.4982, 0.2899]])


## 2. Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on whice they are stored.

In [3]:
tensor = torch.rand(4, 5)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([4, 5])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Operations on Tensors

A large number of operations - over 1200.
From basic: arithmetic, linear algebra, matrix manipulation (transposing, inxdexing, slicing).

In [4]:
# Numpy-like indexing and slicing ( remainder: row, column)
tensor = torch.ones(3, 3)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}") # ... is equal to ':,' dim(Tensor)-1 

tensor[:, 2] = 404 # Change the third column to 404
print(tensor)


# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)

print(t1)


# Arithmetic operations
y1 = tensor @ tensor.T # Matrix multiplication
z1 = tensor * tensor # Element-wise product

print("y1 (matmul):\n", y1)
print("z1 (mul):\n", z1)

First row: tensor([1., 1., 1.])
First column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[  1.,   1., 404.],
        [  1.,   1., 404.],
        [  1.,   1., 404.]])
tensor([[  1.,   1., 404.,   1.,   1., 404.,   1.,   1., 404.],
        [  1.,   1., 404.,   1.,   1., 404.,   1.,   1., 404.],
        [  1.,   1., 404.,   1.,   1., 404.,   1.,   1., 404.]])
y1 (matmul):
 tensor([[163218., 163218., 163218.],
        [163218., 163218., 163218.],
        [163218., 163218., 163218.]])
z1 (mul):
 tensor([[1.0000e+00, 1.0000e+00, 1.6322e+05],
        [1.0000e+00, 1.0000e+00, 1.6322e+05],
        [1.0000e+00, 1.0000e+00, 1.6322e+05]])


## 4. Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memore locations, and changing one will change the other.

In [5]:
# Tensor to NumPy array
t1= torch.ones(5)
n1 = t1.numpy()

print(f"t1: {t1}")
print(f"n1: {n1}")


# NumPy array to Tensor
n2 = np.ones(5)
t2 = torch.from_numpy(n2)

print(f"n2: {n2}")
print(f"t2: {t2}")


# A change in one reflects on the other.
t1.add_(-1) # first pair
np.add(n2, +1, out=n2) # second pair

print("After changing:")

print(f"t1: {t1}")
print(f"n1: {n1}")

print(f"n2: {n2}")
print(f"t2: {t2}")

t1: tensor([1., 1., 1., 1., 1.])
n1: [1. 1. 1. 1. 1.]
n2: [1. 1. 1. 1. 1.]
t2: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
After changing:
t1: tensor([0., 0., 0., 0., 0.])
n1: [0. 0. 0. 0. 0.]
n2: [2. 2. 2. 2. 2.]
t2: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Notes:

By default, all tensors in PyTorch are created on the CPU. This is important because if you want to use an accelerator, such as a GPU, be sure to first transfer the tensors to that device using the $.to(<device>)$ method and then check its availability in the system. However, be careful because improper use may lead to errors or decreased performance.

## Conclusion

- We learned how to work with Tensors.
- Changes in one object automatically reflect in another if they are linked via memory.
- This saves resources, but requires careful handling of inplace-operations.
